# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/nbdev-hello-world',
                'doc_host': 'https://laz4rz.github.io',
                'git_url': 'https://github.com/laz4rz/nbdev-hello-world',
                'lib_path': 'nbdev_hello_world'},
  'syms': { 'nbdev_hello_world.core': { 'nbdev_hello_world.core.foo': ( 'https://laz4rz.github.io/core.html#foo',
                                                                        'https://github.com/laz4rz/nbdev-hello-world/blob/master/nbdev_hello_world/core.py#L7'),
                                        'nbdev_hello_world.core.say_hello': ( 'https://laz4rz.github.io/core.html#say_hello',
                                                                              'https://github.com/laz4rz/nbdev-hello-world/blob/master/nbdev_hello_world/core.py#L10')}}}